---
## ansible-playbook playbooks/ec2-demo.yml
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Provision a set of instances
      ec2:
        key_name: unong-dlab
      register: ec2
    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: ec2.instances
